### ISSUE TITLE
Could you share the 'libs' folder? What is inside the folder?

### ISSUE THREAD

**Issue by avinashboy** [gigacycle/AndroidHidUsbRelayControl#2]
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
 // rest of line 
}

**Comment by gigacycle** [comment]
All imported libraries are :

import android.content.Context;
import android.hardware.usb.UsbDevice;
import android.hardware.usb.UsbDeviceConnection;
import android.hardware.usb.UsbEndpoint;
import android.hardware.usb.UsbManager;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.Switch;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

So there is nothing extra lib!

**Comment by avinashboy** [comment]
Thanks
